query atomicassets_assets ($asset_id: bigint!) {
  atomicassets_assets(where: {asset_id: {_eq: $asset_id}}) {
    asset_id
    atomicassets_template {
      immutable_data
      max_supply
      issued_supply
      burnable
      transferable
    }
    owner
    template_id
    schema_name
    collection_name
    atomicassets_assets_backed_tokens {
      token_symbol
      amount
    }
    immutable_data
    atomicassets_asset_mints {
      template_mint
    }
    atomicassets_collection {
      market_fee
    }
  }
}
